### ISSUE TITLE
提交指纹-[zfsoft-oa]

### ISSUE THREAD

**Issue by finder6** [0x727/FingerprintHub#17]
### 测试目标

http://222.219.184.165/index.do

### 指纹的Yaml规则

name: zfsoft-oa
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - zfoausername
    favicon_hash: []

**Comment by cn-kali-team** [comment]
重命名了正方协同办公oa
