### ISSUE TITLE
spray中已支持了fingerprinthub作为补充指纹库

### ISSUE THREAD

**Issue by M09Ic** [0x727/FingerprintHub#191]
https://github.com/chainreactors/spray/releases/tag/v0.9.4

感谢您一直依赖对指纹库的维护, spray也使用了您的工作成果.  采用了web_fingerprint_v3.json作为数据源, 如有破坏性更新, 方便的话可以提醒我.

**Comment by cn-kali-team** [comment]
自己提pr添加到表格里
