### ISSUE TITLE
根据空间搜索引擎语法自动生成指纹规则功能有Bug

### ISSUE THREAD

**Issue by Wnltc** [0x727/FingerprintHub#195]
类型是favicon，但hash不是纯hash
![image](https://github.com/user-attachments/assets/178cc625-2cae-4d60-9747-a1ae75154a67)

生成的正则表达式，括号没有转义也没有闭合
![image](https://github.com/user-attachments/assets/d95ad5ed-b03b-4e9b-a1ee-8217a57882a1)

**Comment by cn-kali-team** [comment]
语法太复杂了，一个也不标准，手动改了，感谢反馈
