### ISSUE TITLE
师傅，请教下

### ISSUE THREAD

**Issue by j4vaovo** [0x727/FingerprintHub#57]
### 测试目标

-

### 指纹的Yaml规则

[FingerprintHub](https://github.com/0x727/FingerprintHub)/[plugins](https://github.com/0x727/FingerprintHub/tree/main/plugins)/tags.yaml

apache-nifi:
  - - nifi

name: apache-nifi
priority: 1
nuclei_tags:
  - [nifi]

为什么action自动更新的时候没有获取到这个模板呢= =
https://raw.githubusercontent.com/projectdiscovery/nuclei-templates/main/misconfiguration/apache/apache-nifi-unauth.yaml

**Comment by cn-kali-team** [comment]
我看了一下日志，因为那天我点合并太快了，atcion运行完成正要push的时候，原来的仓库已经被修改了，导致提交冲突，我应该等到上一个action运行完再合并第二个的，我现在本地跑一次。
